"""empty message

Revision ID: 0e757c44ef3c
Revises: 52ee4d854985
Create Date: 2020-12-19 21:55:23.011628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e757c44ef3c'
down_revision = '52ee4d854985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_interests', sa.Column('interests_id', sa.Integer(), nullable=False))
    op.drop_constraint('users_interests_interest_id_id_fkey', 'users_interests', type_='foreignkey')
    op.create_foreign_key(None, 'users_interests', 'interests', ['interests_id'], ['id'])
    op.drop_column('users_interests', 'interest_id_id')
    op.drop_column('users_interests', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_interests', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('users_interests', sa.Column('interest_id_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users_interests', type_='foreignkey')
    op.create_foreign_key('users_interests_interest_id_id_fkey', 'users_interests', 'interests', ['interest_id_id'], ['id'])
    op.drop_column('users_interests', 'interests_id')
    # ### end Alembic commands ###
