"""empty message

Revision ID: 201ce4160e74
Revises: aace1605b051
Create Date: 2020-12-19 22:03:55.146315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201ce4160e74'
down_revision = 'aace1605b051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_interests',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('interests_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['interests_id'], ['interests.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'interests_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_interests')
    # ### end Alembic commands ###
