"""empty message

Revision ID: 3efbe035a8d7
Revises: 201ce4160e74
Create Date: 2020-12-19 23:44:49.834746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efbe035a8d7'
down_revision = '201ce4160e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_friendship',
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'accepted', 'second_level', name='friendshipstatus'), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['interests.id'], ),
    sa.PrimaryKeyConstraint('requester_id', 'target_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_friendship')
    # ### end Alembic commands ###
