"""empty message

Revision ID: 52f22b4c1739
Revises: 3efbe035a8d7
Create Date: 2020-12-20 00:42:15.539881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f22b4c1739'
down_revision = '3efbe035a8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'creator_id')
    # ### end Alembic commands ###
