"""empty message

Revision ID: 64cab6c02ec0
Revises: 0e757c44ef3c
Create Date: 2020-12-19 21:57:14.123077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cab6c02ec0'
down_revision = '0e757c44ef3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_interests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interests_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interests_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'interests_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_interests')
    # ### end Alembic commands ###
